INSERT INTO users_user(name, age, nick_name, role, account_username, account_password) values('Tony Stark', 20,  'Iron Man', 'ADMIN', 'jarvis_master', '$2a$10$1qenYmTRyCfD6RgG4Iy8au0jsC3.y/z2rMUOaAdzUUuYZDKGBX.fC');
INSERT INTO users_user(name, age, nick_name, role, account_username, account_password) values('Thor Odinson', 21, 'Thor', 'USER',  'mjolnir_master', '$2a$10$Q6WOtWM03lIWNCr.W2kX2.rk9UeSkfy4ZJW9/6KfMNGUtnjzhF6p2');
INSERT INTO users_user(name, age, nick_name, role, account_username, account_password) values('Steve Rogers', 22, 'Captain America', 'USER', 'vibranium_master', '$2a$10$3NA4nC.7zln9vk2pz/TqqeYmdTZgVP248Pa2qO6enAXGC47vgvKCi');
INSERT INTO users_user(name, age, nick_name, role, account_username, account_password) values('Bruce Banner', 23, 'Hulk', 'USER', 'gammaray_master', '$2a$10$mDxM0S8itR66UvydCR/D5u2lnDn4ONYgPJuH33stKHjxIXUlXR2Ba');
INSERT INTO users_user(name, age, nick_name, role, account_username, account_password) values('Hank Pym', 24, 'Ant Man', 'USER', 'ant_master', '$2a$10$.pa6BO..jLVXhtMNcj27Gefw..bVuWVeUXDBpDWFE90Yson4tUTTW');
INSERT INTO users_user(name, age, nick_name, role, account_username, account_password) values('Peter Parker', 16, 'Spider Man', 'USER', 'spider_master', '$2a$10$gke/H5d5xI9qzG0r0qcCpe9Ilmictjk7Djmh9Klq9Mt1ZAjYQWJMG');

INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('Titanic', 'A love story set against the backdrop of the ill-fated maiden voyage of the RMS Titanic.', 'James Cameron', '1997-12-19','https://cdn.europosters.eu/image/1300/posters/pokemon-pikachu-neon-i71936.jpg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'Francis Ford Coppola', '1972-03-24','pica.jpeg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('The Dark Knight', 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.', 'Christopher Nolan', '2008-07-18','https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold through the perspective of an Alabama man with an IQ of 75.', 'Robert Zemeckis', '1994-07-06','https://musicart.xboxlive.com/7/40025100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', 'Christopher Nolan', '2010-07-16','https://flhsnavigator.com/wp-content/uploads/2021/10/url-4.jpeg?w=810');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'Lana Wachowski, Lilly Wachowski', '1999-03-31','https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('Fight Club', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'David Fincher', '1999-10-15','https://image.tmdb.org/t/p/original/eTfuFbfeKVP53AfIYCVomvIN0rC.jpg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 'A hobbit named Frodo Baggins is recruited to join a quest to destroy the One Ring and save Middle-earth from Sauron.', 'Peter Jackson', '2001-12-19','https://upload.wikimedia.org/wikipedia/en/5/53/L.O.R.D_Legend_of_Ravaging_Dynasties_poster.jpeg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'Ridley Scott', '2000-05-05','https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24674_p_v13_bc.jpg');
INSERT INTO FILMS_FILM (title, description, director, release_date, img_Path) VALUES ('Spider-Man', 'When bitten by a genetically modified spider, nerdy high school student Peter Parker gains newfound powers that he uses to fight crime and corruption.', 'Sam Raimi', '2002-05-03','https://m.media-amazon.com/images/M/MV5BODY2MTAzOTQ4M15BMl5BanBnXkFtZTgwNzg5MTE0MjI@._V1_.jpg');

INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('An emotional rollercoaster. A masterpiece!', 5, 1, 1);  -- Review for Titanic
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('The best gangster movie ever made.', 5, 2, 2);  -- Review for The Godfather
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('A thrilling experience with an amazing performance by Heath Ledger.', 4, 3, 3);  -- Review for The Dark Knight
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('An inspiring story that will stick with you.', 5, 4, 4);  -- Review for Forrest Gump
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('Mind-bending and visually stunning.', 4, 5, 5);  -- Review for Inception
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('A groundbreaking sci-fi film that changed the genre.', 5, 1, 6);  -- Review for The Matrix
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('Dark, gritty, and thought-provoking.', 4, 3, 7);  -- Review for Fight Club
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('An epic journey that is beautifully crafted.', 5, 2, 8);  -- Review for The Lord of the Rings: The Fellowship of the Ring
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('A great story of revenge with stunning visuals.', 4, 2, 9);  -- Review for Gladiator
INSERT INTO REVIEW (review_text, rating, user_id, film_id) VALUES ('A fun and exciting superhero movie.', 4, 1, 10);  -- Review for Spider-Man